[package]
name = "ruma-identifiers-validation"
description = "Validation logic for ruma-identifiers and ruma-identifiers-macros"
homepage = "https://www.ruma.io/"
repository = "https://github.com/ruma/ruma"
authors = [
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Jonas Platte <jplatte@posteo.de>",
]
license = "MIT"
version = "0.4.0"
edition = "2018"

[dependencies]
arbitrary = { version = "1", optional = true, features = ["derive"] }

[package.metadata.docs.rs]
all-features = true

[features]
compat = []
