[package]
authors = ["Wim de With <wf@dewith.io>"]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix application service API."
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-appservice-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma"
version = "0.3.0"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
unstable-exhaustive-types = []
helper = ["ruma-client-api", "tracing"]
client = []
server = []
arbitrary = ["arbitrary_cr", "ruma-api/arbitrary", "ruma-events/arbitrary", "ruma-serde/arbitrary", "ruma-client-api/arbitrary", "ruma-common/arbitrary"]

[dependencies]
ruma-api = { version = "0.17.1", path = "../ruma-api" }
ruma-client-api = { version = "0.11.0", path = "../ruma-client-api", features = ["client"], optional = true }
ruma-common = { version = "0.5.4", path = "../ruma-common" }
ruma-events = { version = "0.23.1", path = "../ruma-events" }
ruma-identifiers = { version = "0.19.4", path = "../ruma-identifiers" }
ruma-serde = { version = "0.4.1", path = "../ruma-serde" }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.61"
tracing = { version = "0.1.25", optional = true }
arbitrary_cr = { package = "arbitrary", version = "1", optional = true, features = ["derive"] }

[dev-dependencies]
matches = "0.1.8"
serde_yaml = "0.8.17"
